version: '3.9'

networks:
  app:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - ./apps/cms/.env.production
    volumes:
      - ./postgres/:/var/lib/postgresql/data
    restart: unless-stopped
  cms:
    container_name: cms
    build:
      context: .
      dockerfile: ./apps/cms/Dockerfile.production
    ports:
      - '1337:1337'
    env_file:
      - ./apps/cms/.env.production
    environment:
      - STRAPI_VERSION=4.5.3
    volumes:
      - ./:/app/
      - /app/node_modules/
    restart: unless-stopped
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.production
    ports:
      - '3000:3000'
    env_file: ./.env.production
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app
