FROM node:16.17.0-alpine

# add turborepo
RUN apk add --no-cache libc6-compat
RUN npm install -g turbo pnpm

#add strapi
RUN npm install -g @strapi/strapi@${STRAPI_VERSION}

# Set working directory
WORKDIR /app

# Install app dependencies
COPY  ["package.json", "./"]

# Copy source files
COPY . .

# Install app dependencies
RUN pnpm install

EXPOSE 1337

CMD pnpm run production
